### ISSUE TITLE
Make don't works

### ISSUE THREAD

**Issue by henriquebeira** [retrodeluxe/rlengine-msx#6]
Hi! 
When I run "make", something wrong happen. 
Someone can help me? 

Thanks! :-) 

![msx](https://user-images.githubusercontent.com/2248964/36634914-e060fc3e-198a-11e8-9ae0-484b58001b8e.png)

**Comment by retrodeluxe** [comment]
Hi Henrique,
   the error shows a syntax error. Did you change anything?
  
   which version of ubuntu are you using?

regards,
E.-

**Comment by henriquebeira** [comment]
Hi! Many thanks for your reply! :-D 

I just installed Ubuntu 17.04 (32 Bits) on a VM, download RLENGINE zip file, and type "make", as you see on my photo. :-) 
Did I need to install some additional package? 

Thanks again!

**Comment by retrodeluxe** [comment]
Hi,
   allright, I think the problem might be the 32bit part.

   the main.mk script currently assumes if you use linux is a 64bit version (hence the x86_64 directory).

   you can try to download the i386 version of sdcc and put it in the prebuilts folder, then edit build/ main.mk.

   but I think not all rom sizes will work because the 3.6.5 version in prebuilts is patched.

If you confirm this is the problem I will create a ticket to add support for 32 bit.

**Comment by henriquebeira** [comment]
Thanks again! :-) 

Well, i downloaded i386 version of SDCC (3.6.0), and put it inside the prebuilts/x86_64 folder, and edited build/main.mk 
I run "make" and a "map_test.rom" was made and running on MSX emulator! :-) 

[map_test.zip](https://github.com/retrodeluxe/rlengine-msx1/files/1760920/map_test.zip)

But others do not worked, please see my image. 

![virtualbox_ubuntu_26_02_2018_22_37_56](https://user-images.githubusercontent.com/2248964/36705837-f0a81016-1b45-11e8-80c6-fe26a852f781.png)

Maybe needs to add support for 32 bit... 

Anywaym thanks in advance! :-D

**Comment by retrodeluxe** [comment]
Hi,
   yes, the -bo option is what I meant about the patched sdcc. 

   I will create a ticket to fix this problem.

   also if you like you can try to build sdcc with the patch. Is the project sdcc-msx in this same GitHub.

regards,
E.-

**Comment by henriquebeira** [comment]
Hello! 
I see... I'll make another tests for now... 
Thanks for opening a ticket about it!
